### ISSUE TITLE
Release for ROS noetic?

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/ur_msgs#13]
As more and more people are migrating towards ROS noetic it might be good to release this repository to ROS noetic, as well. As this package has very little (core) dependencies, it shouldn't be too much of an effort, right?

**Comment by gavanderhoorn** [comment]
Unfortunately there are *always* things to patch up before/during/after a release, so it's never a *next-next-next* affair, but see ros/rosdistro#29661.

**Comment by gavanderhoorn** [comment]
Closing as I expect the PR to `ros/rosdistro` to get merged.

Note: it will take some time for things to get synced to the main repositories, as we've just had a Noetic sync ([discourse](https://discourse.ros.org/t/preparing-for-noetic-sync-2021-05-24/20540)).
