### ISSUE TITLE
Version for ros2?

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/ur_msgs#17]
Thanks for approving #12 @gavanderhoorn. While preparing the release I stumbled upon two questions:

1. What should be the version bump for the ROS2 version? I would intuitively suggest `2.0.0` as we are starting a different track here. One could argue, that the messages themselves are still the same as with `1.3.4`, though.
2. Just to confirm: Once the version has been bumped and tagged, I would create a `foxy` branch on that commit and release all (Foxy, Galactic and Rolling) from that branch. A quick *ack* on that from your side @gavanderhoorn would be very much apreciated.

**Comment by gavanderhoorn** [comment]
> 1\. What should be the version bump for the ROS2 version? I would intuitively suggest `2.0.0` as we are starting a different track here. One could argue, that the messages themselves are still the same as with `1.3.4`, though.

So this is one of the disadvantages of storing ROS 1 and ROS 2 artefacts in the same repository: you cannot have two tags with the same name in a repository. This immediately means you cannot use `1.3.4` for the ROS 2 release -- even though that would make sense (as there haven't been any changes to the artefacts for which versioning really matters, ie: the message definitions).

I would have personally liked us to keep using the current version (for the reason I stated above), but that's impossible.

Bumping the major to `2` is probably the easiest option in this case.

> 2\. Just to confirm: Once the version has been [..] tagged, I would create a `foxy` branch on that commit and release all (Foxy, Galactic and Rolling) from that branch.

Ideally we'd create a release branch first, then update changelogs etc, merge those changes into the devel branch, then use a sync PR to get those changes onto the release branch (see #15 for the last ROS 1 example) and then release from the release branch.

Seeing as the release branch doesn't exist yet, you could create the release branch after updating changelogs and tagging. Then you wouldn't need a sync PR.

I'd prefer it if you'd use one for the next release though.

**Comment by gavanderhoorn** [comment]
I'm going to close this, as I believe you've already made sufficient progress.
