### ISSUE TITLE
How to Install this package for Ros2?

### ISSUE THREAD

**Issue by robertokcanale** [ros-industrial/ur_msgs#18]
I am trying to install  https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver   but I am unable because of the following message: 

```
executing command [sudo -H apt-get install -y ros-foxy-ur-msgs]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-foxy-ur-msgs
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-foxy-ur-msgs] failed
  apt: Failed to detect successful installation of [ros-foxy-ur-msgs]
```

How can I install it? should I just include it as a regulare package?

**Comment by gavanderhoorn** [comment]
You seem to already have opened https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/issues/365, which would be a better place to discuss this.

Closing this one.
