### ISSUE TITLE
Set_io service issue

### ISSUE THREAD

**Issue by BilboFromBitola** [ros-industrial/ur_msgs#19]
Hey, I am using a UR10e robot and ROS2 Humble. When calling the ur_msg/srv/SetIO service from terminal trying to set a certain I/O pin to 1 or 0 i get a response that it is unable to do this setting of the pin value. I'd like to mention that it is possible for me to connect to Rviz and control the robot this way without an issue. To me it seems that the service can't comunicate to the robot so I would like some help on this one. Thanks.

**Comment by fmauch** [comment]
Hi, this seems like an issue best handled inside the [driver's repository](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver). Please reopen an issue there (Sorry for being picky about this, but this will keep things together where they belong.)

When you reopen your issue there, please link it to this issue and post the commands and the complete terminal output
* used for starting the driver
* used to set the I/O pin

This should help figuring out what is going wrong.
Thank you!
